### ISSUE TITLE
[Feature] Modificar cita

### ISSUE THREAD

**Issue by abalderas** [ruizrube/acsa-chatbot#11]
## Información
El usuario solicita modificar su cita con el médico. El sistema comprueba si tiene una cita y, en caso afirmativo, le consulta/propone una nueva cita. Si el usuario acepta, reserva la nueva cita y cancela la anterior.

## Artefactos a editar:
- Configuración en DialogFlow: intents, entities, etc.
- Código en backend
- Página de la wiki

**Comment by abalderas** [comment]
Borrador en el wiki:  [modificar-cita](https://github.com/ruizrube/acsa-chatbot/wiki/Casos-de-uso#cdu-modificar-cita)

**Comment by ruizrube** [comment]
Por facilidad de implementación y para no tener que repetir la secuencia de intents y demás, lo implemento de modo que, tanto el caso de uso de solicitar y modificar sean iguales, solo difieren en las frases de entrenamiento. Tanto uno como otro cancelarán cualquier cita que tenga pendiente el usuario antes de insertar la nueva. En el caso en que el usuario ya tuviese una cita, se avisará de tal acontecimiento.

**Comment by ruizrube** [comment]
Faltaría modificar la descripción del caso de uso, para cerrar el issue. No lo hago hasta que no lo pruebes tu y me des el ok de esto

**Comment by abalderas** [comment]
Lo veo bien. He modificado el caso de uso en base al funcionamiento. Si lo ves correcto, cerramos el issue.
