### ISSUE TITLE
[Feature] Recibir ayuda

### ISSUE THREAD

**Issue by ruizrube** [ruizrube/acsa-chatbot#15]
## Información
El bot deberá ofrecer información contextual al usuario de qué es lo que puede hacer en cada momento de la interacción.

## Artefactos a editar:
- Configuración en DialogFlow: intents, entities, etc.
- Código en backend
- Página de la wiki

**Comment by abalderas** [comment]
Creado el intent usuario.help
Es un caso de uso sencillo.
Le he dado varias frases de entrenamiento y simplemente responde con la información para empezar. Se podría ampliar dando información de otras acciones a realizar.
