### ISSUE TITLE
[Feature] Mejorar la comprensión del agente

### ISSUE THREAD

**Issue by ruizrube** [ruizrube/acsa-chatbot#17]
## Información
Añadir, al menos, 10 frases de entrenamiento para cada intent

## Artefactos a editar:
- Configuración en DialogFlow: intents, entities, etc.

**Comment by abalderas** [comment]
Añadidas 10 frases al intent user.content

**Comment by abalderas** [comment]
Completado hasta 10 frases al intent user.welcome

**Comment by abalderas** [comment]
Completado hasta 10 frases el intent user.identify

**Comment by abalderas** [comment]
Añadidas 10 frases al intent user.revoke

**Comment by abalderas** [comment]
Completadas hasta 10 frases el intent appointment.query

**Comment by abalderas** [comment]
Completadas hasta 10 frases el intent appointment.modify

**Comment by abalderas** [comment]
- Completadas hasta 10 frases el intent appointment.cancel
- Completadas hasta 12 frases el intent appointment.request
- Completadas hasta 12 frases el intent user.bye

**Comment by abalderas** [comment]
Añadidas 10 frases al intent general.clinic
