### ISSUE TITLE
[Bug] usuario, ¿puedes repetir?

### ISSUE THREAD

**Issue by abalderas** [ruizrube/acsa-chatbot#21]
**Descripción**
Cuando el bot te lee el consentimiento.
Si el usuario responde 'no', la conversación se acab 'set intent as end of conversation'

Sin embargo, el chatbot se queda en esa frase: "Camen, ¿puedes repetir?"

**Pasos para reproducir el error**
1. Hola
2. Mi DNI es 444
3. Cosentimiento, acepta?
4. No
5. Carmen, ¿puedes repetir?

**Comment by ruizrube** [comment]
Ya no debe suceder

**Comment by abalderas** [comment]
Perfecto.
