### ISSUE TITLE
[Bug] Nueva cita (gestión horas)

### ISSUE THREAD

**Issue by abalderas** [ruizrube/acsa-chatbot#32]
**Descripción**
Funciona correctamente, pero me da cita a horas poco apropiadas. (00:10, 00:25, etc.). Habría que fijar un horario de citas.

**Comment by abalderas** [comment]
1. Permitir solo los días ofrecidos
2. Permitir solo las horas ofrecidas
3. No ofrecer tampoco días festivos

Caso:
El agente me ofrece tres opciones (31 de diciembre, 1 y 2 de enero), si le digo 3 de enero cuela (punto 1)
Además, me ofrece las 8:15, 8:30 y 8:45. Le digo las 8 y cuela también (punto 2)
Puede ser una opción en un momento dado, que el usuario solicite una fecha no ofrecida. Habría que comprobar que esa fecha está libre en la agenda.

Por otro lado, habría que limitar la agenda a días laborables (punto 3).

**Comment by ruizrube** [comment]
Veo mejor darle libertad al usuario para elegir la fecha y hora que quiera,
aunque no sea una de las propuestas. Lo que tengo que implementar es que
compruebe la disponibilidad nuevamente en el último paso antes de registrar
la cita.

Vale también a lo del punto 3, aunque realmente es una simulación, la
agenda de citas la proporcionaría la api

**Comment by ruizrube** [comment]
Ahora se le da libertad, pero controlada. Solo se ofrecen dias de lunes a viernes y de 8 a 15. Además se comprueba que el mismo médico no tenga asignado cita en el mismo intervalo de tiempo. 
Estas comprobaciones se hacen tanto en los ofrecimientos, como a la hora de confirmar la cita, para los casos donde se indique una fecha/hora no propuesta por el sistema
