### ISSUE TITLE
[Feature] Cerrar sesión al despedirse

### ISSUE THREAD

**Issue by abalderas** [ruizrube/acsa-chatbot#33]
**Descripción**
Permite coger cita a usuario que no ha aceptado las condiciones.
Entiendo que puede ser porque el contexto no se destruye.

**Pasos para reproducir el error**

1. Accedo como usuario  con DNI 111, que ya ha dado consentimiento
2. Hago gestión y digo adiós
3. Vuelvo a interacturar indicando que mi DNI es otro (el de un usuario que no ha aceptado consentimiento)+
4. Me deja seguir con la gestión de la cita

**Comment by ruizrube** [comment]
Sure. Además lo mismo sucede al iniciar sesión que no se eliminaban los contextos previos
