### ISSUE TITLE
[Feature] [Proposal] Página web con las condiciones de uso

### ISSUE THREAD

**Issue by abalderas** [ruizrube/acsa-chatbot#35]
## Información

Hay que incoporar las condiciones de uso. Es un texto largo que se encuentra en el documento del comité de ética, página 10.

## Propuesta

Incorporarlo a una página web dentro de la web de demostración (por ejemplo, http://acsa-chatbot.es/condiciones.html).
El chatbot te enlazará la página y te preguntará si las aceptas.

## Artefactos a editar:
- Configuración en DialogFlow: intent user.consent
- Código en backend: consentimiento.html
- Página de la wiki.

**Comment by abalderas** [comment]
@ruizrube yo me puedo encargar si te parece bien hacerlo así.

**Comment by ruizrube** [comment]
Vale, me parece bien. Habría que activar también alguna "rich response "
para el caso que se use el bot desde el propio Google Assistant

**Comment by abalderas** [comment]
Ok, yo me encargo.

**Comment by abalderas** [comment]
Creado custompayload para el link
