### ISSUE TITLE
[Feature] Cancelación durante el proceso de cita

### ISSUE THREAD

**Issue by abalderas** [ruizrube/acsa-chatbot#36]
**Descripción**
Si el usuario cancelaba el alta de una cita durante el proceso de selección de días u horas, el agente se perdía y saltaba el fallback por defecto.

**Pasos para reproducir el error**
1. Hola - _Quiero cita con mi médico_
2. ¿Cómo? - _Telefónica_
3. Le puedo ofrecer el día 1, el día 2, ... - _Cancelar_
4. Pepe, no le entiendo.

**Comment by abalderas** [comment]
Solucionado, he creado el intent _appointment.request - no_

**Comment by ruizrube** [comment]
El commit hacia referencia al issue 34, lapsus mío.
