### ISSUE TITLE
[Bug] Confusión con la hora

### ISSUE THREAD

**Issue by abalderas** [ruizrube/acsa-chatbot#39]
**Descripción**
Le indico la hora que quiero (a.m.) y me tramita dicha hora pero (p.m.)
Detectado en **caso de prueba 3**

**Pasos para reproducir el error**
Chatbot: Podría ofrecerte cita para el jueves 3 de febrero, el viernes 4 de febrero, el lunes 7 de febrero, u otra fecha, ¿cuál prefieres?
Usuario: jueves
Chatbot: Tengo citas disponible para a las **8 horas y 15 minutos**, a las 8 horas y 30 minutos, a las 8 horas y 45 minutos, más tarde u otra fecha, ¿cuál prefieres?
Usuario: 8:15
Chatbot: Le voy a gestionar una nueva cita para el jueves 3 de febrero a las **20 horas y 15 minutos**. ¿La confirmamos?
Usuario: sí
Chatbot: Lo siento, pero a esa hora no hay disponibilidad de cita con su doctor

**Comment by abalderas** [comment]
Si especifico 8:15 am, lo hace bien.

De acuerdo, la cita ha sido registrada correctamente. Su cita es el jueves 3 de febrero a las 8 horas y 15 minutos, en el centro de salud null

**Comment by ruizrube** [comment]
Probablemente relacionado con el mismo problema del #40. A falta de información (am/pm) el sistema busca la fecha/hora más cercana. ¿A que hora hiciste esta prueba? Lo he probado a las 17 de la tarde y efectivamente ocurre. Me gustaría ver si pasa esto mismo pidiendo cita por la mañana.

**Comment by abalderas** [comment]
Lo hice a las 12h aproximadamente

**Comment by ruizrube** [comment]
@abalderas  He hecho el truqui que me dijiste de manipular la hora 
         * 1<=time<=7 -> time=time+12
	 * 8<=tim<=19 -> time=time
	 * 20<=time<=23 -> time=time-12
