### ISSUE TITLE
[Bug] Revisar respuesta centro de salud

### ISSUE THREAD

**Issue by abalderas** [ruizrube/acsa-chatbot#41]
**Descripción**
Respuesta con errores a la consulta sobre centro de salud. Revisar.

**Pasos para reproducir el error**
Usuario: ¿cuál es mi centro de salud?
Chatbot: Su centro de salud, **null**, se encuentra en Hidroavión Numancia, **0y su** teléfono es 956956956

**Comment by ruizrube** [comment]
Era error en la carga de datos. Corregido
