### ISSUE TITLE
[Improvement] Tienes que decir que quieres cita dos veces

### ISSUE THREAD

**Issue by abalderas** [ruizrube/acsa-chatbot#42]
**Descripción**
Cuando inicias la conversación, tienes que decir que quieres cita dos veces. ¿Podría guardarse la pregunta previa a la identificación?

**Pasos para reproducir el error**

1. Usuario: quiero cita con mi médico
2. Chatbot: Para poder gestionar tus citas, debes identificarte como usuario o usuaria del Servicio Andaluz de Salud. ¿Quieres iniciar sesión ahora?
3. Usuario: sí
4. Chatbot: Necesito que me indiques su DNI o su número de tarjeta sanitaria
5. Usuario: 11111111A
6. Chatbot: Hola Pepe Andaluz, ¿cómo puedo ayudarte?
7. Usuario: quiero cita con mi médico
8. Chatbot: ¿Desea que la cita con su médico sea presencial o telefónica?
...

**Propuesta: reducir los pasos previos del 2 al 7** 
1. Usuario: quiero cita con mi médico
2. Chatbot: Para poder gestionar tus citas, debes identificarte como usuario o usuaria del Servicio Andaluz de Salud. ¿Puede indicarme su DNI para inciar sesión?
3. Usuario: 11111111A
4. Chatbot: ¿Desea que la cita con su médico sea presencial o telefónica?
5. ...

**Comment by ruizrube** [comment]
Sí eso lo había pensado alguna vez. 
He pensado en analizar el JSON que se envia con la petición HTTPS del dialogflow y extraer de ahí la lista posible de intents que hacen mathching con la frase de entrada pero mi gozo en un pozo... Solo aparece un único intent, que es el que hace matching más exacto. Esperaba encontrarme ahí todos los intents y el % de confianza de cada uno, pero no...

**Comment by ruizrube** [comment]
Alguna idea @abalderas ?

**Comment by abalderas** [comment]
¿Y que la identificación forme parte del proceso de pedir cita? con un sub-intent del tipo appoinment.request.identify

Habría que quitar el contexto user-identified del general y activarlo una vez que se identifique en el sub-intent.

**Comment by ruizrube** [comment]
Hay tres pre-condiciones: que se haya identificado, que se haya activado y que haya aceptado las condiciones de uso. Pre-condiciones que deben comprobarse en todos los casos de uso, no solo en el de pedir cita. Por eso lo hice así, implementando un intent de fallback para tratar con las precondiciones en lugar de añadir esas 3 preconds en cada cdu..

**Comment by ruizrube** [comment]
Estoy trabajando en esto. Lo que hago es que en cada cdu, se comprueban las precondiciones, si alguna no se cumple, se lanza el cdu correspondiente. Para no perder el hilo de lo que quería el usuaro guardo en un contexto cuál era su última intención, de modo que cuando acabe el cdu auxiliar de, por ejemplo, identificarse, se invoca de nuevo a la intención requerida

**Comment by ruizrube** [comment]
Listo. Ahora cuando se pide cita, se cambia cita, se consulta centro de salud, etc. y alguna de las condiciones no se cumple, se lanza el cdu correspondiente. Y al acabar sigue la ejecución del cdu original

**Comment by ruizrube** [comment]
Ahora, surge un problema derivado
Si vas a pedir cita, el sistema  te pide si quieres la cita presencial o por teléfono (ya que el parámetro es obligatorio). Si el usuario no ha iniciado sesión, se lanza ese caso de uso y al acabar se activa el cdu de pedir cita, por lo que de nuevo te vuelve a pedir si la quieres presencial o telef

**Comment by ruizrube** [comment]
Lo he apañado activando el "enable webhook dialogflow for slot filling". Así se lanza la validación en servidor sin obligar a establecer desde el cliente el parámetro del tipo de cita
