### ISSUE TITLE
[Feature] Identificar usuario

### ISSUE THREAD

**Issue by ruizrube** [ruizrube/acsa-chatbot#5]
## Información
El agente deberá identificar al usuario a través de algún mecanismo de autenticación por definir. Posibilidades:
- Asociar cuenta de google a usuario del SAS
- DNI o NUHSA y código recibido por SMS
- ... 

## Artefactos a editar:
- Configuración en DialogFlow: intents, entities, etc.
- Código en backend
- Página de la wiki

**Comment by ruizrube** [comment]
Propuesta de caso de uso de Identificar Usuario y Autorizar usuario. Se basaría en DNI y código recibido por SMS

**Comment by abalderas** [comment]
Lo del SMS nos complicaría la demostración. En Salud Responde te piden 3 datos para poder gestionar tus citas desde la app:

1. Nº de tarjeta sanitaria
2. Año de nacimiento
3. DNI

**Comment by ruizrube** [comment]
ok, me parece bien, pero el DNI habría que tratarlo como opcional, para el caso de niños

**Comment by ruizrube** [comment]
Lo ideal sería que el usuario configure esto una única vez. Cuando pides cita por la app pones esos datos cuando te la instalas.  ¿Cómo hacemos esto con el bot?
