### ISSUE TITLE
[Feature] Solicitar cita

### ISSUE THREAD

**Issue by abalderas** [ruizrube/acsa-chatbot#7]
## Información
El usuario solicita una cita con el médico. El sistema propondrá la próxima fecha disponible en la agenda del médico que le corresponda si (1) el usuario está registrado, (2) el usuario ha dado su consentimiento para el tratamiento de datos y (3) no tiene ya una cita asignada.

El usuario puede solicitar una cita en su petición. En este caso, deberá comprobarse que esta fecha está disponible en la agenda del médico.

## Artefactos a editar:
- Configuración en DialogFlow: intents, entities, etc.
- Código en backend
- Página de la wiki

**Comment by abalderas** [comment]
Propuesta de caso de uso

**Comment by abalderas** [comment]
En el Escenario alternativo: el usuario ya tiene una cita previa, se cancela la cita antes de coger una nueva. Esto no es así, la cita no se cancela en "Salud Responde" hasta que no tienes la nueva asignada. Lo he rehecho generando primero la nueva cita y eliminando la anterior.

**Comment by ruizrube** [comment]
Me pongo con la implementación de este cdu

**Comment by abalderas** [comment]
Cuando el chatbot te dice esto: "Si lo desea puedo ayudarle a gestionar sus citas médicas. Para ello me tienes que indicar su DNI".
Lo que te sale como usuario es decirle solo el DNI: 12343211F

He incluido una frase que sea solo un número. ¿Puede haber algún problema con esto?

**Comment by ruizrube** [comment]
Creo que no habría que tener problemas, pero....por ejemplo, a la hora de
elegir el día de la cita médica el usuario podría decir el número del día
(1..31), lo que podría provocar que pillará el intent equivocado.. Esto lo
iremos viendo poco a poco segun vayamos haciendo pruebas

**Comment by ruizrube** [comment]
Ya está lista la implementación del escenario principai de este cdu, aunque quedan algunas cosas pendientes. Como este cdu es el más gordo, cerraré aquí este issue, para que se pueda ir probando y voy a ir abriendo ahora otros issues para carencias que tengo ya detectadas
