### ISSUE TITLE
[Feature] Consultar próxima cita

### ISSUE THREAD

**Issue by abalderas** [ruizrube/acsa-chatbot#8]
## Información
El usuario consulta cuál es su próxima cita. El sistema consulta si tiene una cita y, en caso afirmativo, le indica cuándo es.

## Artefactos a editar:
- Configuración en DialogFlow: intents, entities, etc.
- Código en backend
- Página de la wiki

**Comment by abalderas** [comment]
Esto suponiendo que un usuario no puede tener asignada más de una cita con su médico, por tanto, no hay que preguntarle qué cita quiere modificar, sino simplemente cambiar la nueva cita por la que ya tenía.

**Comment by ruizrube** [comment]
Tengo esa duda, SaludResponde te deja pedir cita teniendo ya una?

**Comment by ruizrube** [comment]
Antes de realizar cualquier acción persistente en el sistema habría que solicitar confirmación. "le voy a asignar una cita para el dia tal a tal hora. ¿está usted seguro?" o algo así....

**Comment by abalderas** [comment]
No. Tengo una cita en la app. Si entro en la gestión de citas, me aparece la fecha de la próxima cita con tres opciones:

1. Anular Cita
2. Cambiar Cita
3. Guardar en el calendario

**Comment by ruizrube** [comment]
Y luego hay otro tema que hay que pensar bien: ¿cómo el usuario elige la fecha /hora?

![Screenshot_2021-12-16-16-46-18-506_citamovil saludresponde](https://user-images.githubusercontent.com/790837/146403289-edc3fb9f-c22f-4d0f-8459-cab6fe3edc0a.jpg)

**Comment by ruizrube** [comment]
> No. Tengo una cita en la app. Si entro en la gestión de citas, me aparece la fecha de la próxima cita con tres opciones:
> 
> 1. Anular Cita
> 2. Cambiar Cita
> 3. Guardar en el calendario

mejor más fácil

**Comment by ruizrube** [comment]
lo de elegir la fecha y hora es lo más complicado de este bot, creo.
Una opción podría ser algo como: Tengo disponibilidad para el día 29, la primera a las 08:15 y la última a las 12:45. ¿Te asigno cita este día u otro? 
Hay que darle una buena pensada...

**Comment by abalderas** [comment]
Propuesta simple:
1. Si el usuario no propone fecha: se le propone el primer slot disponible
2. Si el usuario propone fecha: se le propone el slot más cercano de los disponibles

Propuesta menos simple:
1. Si el usuario no propone fecha: se le proponen tres fechas en días consecutivos. Una vez indicado la fecha, se le proponen varios slots disponibles en la fecha seleccionada
2. Si el usuario propone fecha: se le proponen varios slots para su cita, lo más cercanas posibles a la petición.

**Comment by ruizrube** [comment]
Creo que lo de el usuario diga el día que quiere me parece un poco fantasioso, como funciona aquí la atención primaría... Te me gusta lo de ir ofreciendo 3 alternativas. ¿y algo así?
- quiero cita
- podría ofrecerte cita para el día 1 por la mañana, 2 por la mañana, 3 por la tarde u otra fecha, ¿cual prefieres?
- oftra fecha
- podría ofrecerte cita para el 4 por la mañana, el 5 por la tarde, o el 6 por la mañana u otra fecha
- quiero el dia 6
- ok, tengo citas a las 08:00, 08:10, 08:20,  más tarde u otro dia.
-  mas tarde
- ok, tengo citas a las 08:30, 08:40, 08:50, más tarde u otro dia
- mas tarde
- tengo cita a las 09:00 u otro día
- otro día
...

**Comment by abalderas** [comment]
Sí, me parece bien. Es sencilla para el usuario e implementable
